# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  subcategories:

  - title: Overview
    items:
    - title: Introduction
      url: /

    - title: Supported features
      url: /product1/mydoc_supported_features.html
      
    - title: About the theme author
      url: /product1/mydoc_about.html  

    - title: Support
      url: /product1/mydoc_support.html   

  - title: Get started

    items:
    - title: 1. Build the default project
      url: /product1/mydoc_getting_started.html

    - title: 2. Add a new project
      url: /product1/mydoc_adding_new_projects.html

    - title: 3. Decide on your project's attributes
      url: /product1/mydoc_decide_on_attributes.html

    - title: 4. Set the configuration options
      url: /product1/mydoc_configuration_settings.html
    
    - title: 5. Customize the conditions file
      url: /product1/mydoc_conditions_file_customization.html
    
    - title: 6. Configure the sidebar
      url: /product1/mydoc_configure_sidebar.html
    
    - title: 7. Configure the top navigation
      url: /product1/mydoc_top_navigation.html

    - title: 8. Customize the URL generator
      url: /product1/mydoc_url_generator_customization.html
      
    - title: 9. Set up Prince XML
      url: /product1/mydoc_princexml_setup.html

    - title: 10. Configure the build scripts
      url: /product1/mydoc_build_scripts.html
      
  - title: Authoring
    
    items:
    - title: Pages
      url: /product1/mydoc_pages.html

    - title: WebStorm Text Editor
      url: /product1/mydoc_webstorm_text_editor.html
      
    - title: Conditional logic
      url: /product1/mydoc_conditional_logic.html
      
    - title: Content reuse
      url: /product1/mydoc_content_reuse.html
      
    - title: Collections
      url: /product1/mydoc_collections.html
      
  - title: Navigation
    
    items:
    - title: Sidebar navigation
      url: /product1/mydoc_sidebar_navigation.html
      
    - title: YAML tutorial in the context of Jekyll
      url: /product1/mydoc_yaml_tutorial.html

    - title: Tags
      url: /product1/tags.html
      
    - title: Series
      url: /product1/mydoc_series.html
      

  - title: Formatting
    
    items:
    - title: Tooltips
      url: /product1/mydoc_adding_tooltips.html
      
    - title: Alerts
      url: /product1/mydoc_alerts.html

    - title: Icons
      url: /product1/mydoc_icons.html

    - title: Images
      url: /product1/mydoc_images.html

    - title: Labels
      url: /product1/mydoc_labels.html

    - title: Links
      url: /product1/mydoc_hyperlinks.html

    - title: Navtabs
      url: /product1/mydoc_navtabs.html

    - title: Video embeds
      url: /product1/mydoc_video_embeds.html
    
    - title: Tables
      url: /product1/mydoc_tables.html
      
    - title: Syntax highlighting
      url: /product1/mydoc_syntax_highlighting.html
      
  - title: Handling reviews
    
    items:
    - title: Commenting on files
      url: /product1/mydoc_commenting_on_files.html

  - title: Publishing
    
    items:
    - title: Build arguments
      url: /product1/mydoc_build_arguments.html

    - title: Themes
      url: /product1/mydoc_themes.html
    
    - title: Link validation
      url: /product1/mydoc_link_validation.html
    
    - title: Check page title consistency
      url: /product1/mydoc_title_checker.html
    
    - title: Generating PDFs
      url: /product1/mydoc_generating_pdfs.html
      
    - title: Excluding files
      url: /product1/mydoc_excluding_files.html
      
    - title: Help APIs and UI tooltips
      url: /product1/mydoc_help_api.html
      
    - title: Search configuration
      url: /product1/mydoc_search_configuration.html

    - title: iTerm profiles
      url: /product1/mydoc_iterm_profiles.html

    - title: Pushing builds to server
      url: /product1/mydoc_push_build_to_server.html
      
    - title: Getting around the password prompts in SCP
      url: /product1/mydoc_no_password_prompts_scp.html
      

  - title: Special layouts
    
    items:
    - title: Knowledge-base layout
      url: /product1/mydoc_kb_layout.html

    - title: Scroll layout
      url: /product1/mydoc_scroll.html

    - title: Shuffle layout
      url: /product1/mydoc_shuffle.html

    - title: FAQ layout
      url: /product1/mydoc_faq.html

    - title: Glossary layout
      url: /product1/glossary.html
      
#      

  - title: Troubleshooting
    
    items:

    - title: Troubleshooting
      url: /product1/mydoc_troubleshooting.html
      
    - title: Adding all project dependencies
      url: /product1/mydoc_install_dependencies.html
      

  - title: Tag archives
    items:

    - title: Tag archives overview
      url: /product1/mydoc_tag_archives_overview.html

      thirdlevel:
      - title: Tag archive pages
        thirdlevelitems:
        - title: Getting started pages
          url: /product1/tag_getting_started.html

        - title: Formatting pages
          url: /product1/tag_formatting.html

        - title: Navigation pages
          url: /product1/tag_navigation.html

        - title: Content types pages
          url: /product1/tag_content_types.html

        - title: Publishing pages
          url: /product1/tag_publishing.html

        - title: Special layout pages
          url: /product1/tag_special_layouts.html

        - title: Collaboration pages
          url: /product1/tag_collaboration.html