sudo: false
language: ruby
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.3
  - 2.4.0
before_install:
    - gem install bundler
script:
    - bundle exec rake test
    - bundle exec rake coveralls:push
bundler_args: --without gui
env:
    global:
        - TEST_ENABLE_COVERAGE=1
