sudo: false
language: ruby
rvm:
  - '2.0'
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - jruby-9.1.5.0
matrix:
    allow_failures:
        - rvm: jruby-9.1.5.0
script:
    - bundle exec rake
    - bundle exec rake test
    - bundle exec rake coveralls:push
bundler_args: --without gui
env:
    global:
        - TEST_ENABLE_COVERAGE=1
