sudo: false
language: ruby
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
script:
    - bundle exec rake test
    - bundle exec rake coveralls:push
bundler_args: --without gui
env:
    global:
        - TEST_ENABLE_COVERAGE=1
