sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
script:
    - bundle exec rake
    - bundle exec rake coveralls:push
bundler_args: --without gui
env:
    global:
        - TEST_ENABLE_COVERAGE=1
