# project definitions
project: mydoc_designers
audience: designers
product: doc
platform: all
version: all
output: web
topnav_title: Jekyll Documentation Theme
homepage_title: Jekyll doc theme for designers
site_title: Jekyll theme for designers
project_folder: mydoc
company_name: Your company
github_editme_path: tomjohnson1492/documentation-theme-jekyll/edit/reviews
disqus_shortname: idrbwjekyll
# variables


sidebar_tagline: Designers
sidebar_version: Version 4.0
theme_file: theme-blue.css

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://documentation-theme-jekyll.com" # the base hostname & protocol for your site


port: 4009

exclude:
  - vendor
  - _site
  - _drafts
  - configs/

# same for all
host: 127.0.0.1
feedback_email: tomjohnson1492@gmail.com

# these settings should work, but they don't seem to apply the right highlighting

highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge


collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

