destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/roby-pdf"
port: 4010
output: pdf
product: roby
print_title: Roby User's Guide
print_subtitle: version 3.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true
